### ISSUE TITLE
About datasets

### ISSUE THREAD

**Issue by heerduo** [Ha0Tang/BiGraphGAN#5]
Can you provide two datasets for me? because of "The requested URL /hao.tang/uploads/datasets/SelectionGAN was not found on this server." Thanks for your help.

**Comment by Ha0Tang** [comment]
How did you download the dataset? Can you provide more details?

**Comment by Ha0Tang** [comment]
Hi, follow these steps to download both datasets,
1. `git clone https://github.com/Ha0Tang/SelectionGAN`
2. `cd SelectionGAN`
3. `cd person_transfer`
4. `sh datasets/download_selectiongan_dataset.sh market_data`

let me know if this does not work for you.

**Comment by heerduo** [comment]
It works for me.
I downloaded SelectionGAN, and in  person_transfer I used "sh datasets/download_selectiongan_dataset.sh market_data", it didnot work. But, today it works, I have no idea about this. Then, I simply copy "http://disi.unitn.it/~hao.tang/uploads/datasets/SelectionGAN/market_data.tar.gz" and  "http://disi.unitn.it/~hao.tang/uploads/datasets/SelectionGAN/". haha, thanks a lot.
