### ISSUE TITLE
Resume the training from the last stage

### ISSUE THREAD

**Issue by Mathilda88** [Ha0Tang/BiGraphGAN#6]
Hi, 

Thanks for the great work. I am trying to resume my training from the checkpoint I've saved before but I don't know where in the code I should do any update. Would you please help me with it.

Thanks,

**Comment by Ha0Tang** [comment]
simply add `--continue_train --which_epoch N --epoch_count N+1` at the end of the command line, for a specific example, please refer to [here](https://github.com/Ha0Tang/BiGraphGAN/blob/master/market_1501/train_market.sh)

**Comment by Mathilda88** [comment]
Thanks a lot
