### ISSUE TITLE
Input of the BiGraphGAN

### ISSUE THREAD

**Issue by yinyiyu** [Ha0Tang/BiGraphGAN#7]
Thank you for your outstanding work. I have read your paper and code, and I found that there are three separate inputs for picture and pos in the paper, but only two inputs from the code. May I ask how this problem was solved?

**Comment by Ha0Tang** [comment]
This is a little trick in implementation. We concatenate both poses as the input, please refer to [this line](https://github.com/Ha0Tang/BiGraphGAN/blob/1a6b2ee104fc95d92193d571c5aad4ca22e201ef/market_1501/models/BiGraphGAN.py#L112).
